spring.application.name=RESOURCE-SERVER
server.port=9001
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:9000/oauth2/jwks
