spring.application.name=EDGE-SERVICE
server.port=9092

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.routes[0].id=account-route
spring.cloud.gateway.routes[0].uri=lb://ACCOUNT-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/account/**

spring.cloud.gateway.routes[1].id=loan-route
spring.cloud.gateway.routes[1].uri=lb://LOAN-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/loan/**

spring.cloud.gateway.routes[2].id=greet-route
spring.cloud.gateway.routes[2].uri=lb://GREET-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/greet/**

spring.cloud.gateway.locator.lower-case-service-id=true
